seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: custom.custom_model.CustomActor # CategoricalMixin # 
    clip_actions: True
    clip_log_std: True
    min_log_std: -5.0
    max_log_std: 2.0
  critic_1:  # see deterministic_model parameters
    class: custom.custom_model.CustomCritic # CategoricalMixin # 
    clip_actions: False
  critic_2:  # see deterministic_model parameters
    class: custom.custom_model.CustomCritic # CategoricalMixin # 
    clip_actions: False
  target_critic_1:  # see deterministic_model parameters
    class: custom.custom_model.CustomCritic # CategoricalMixin # 
    clip_actions: False
  target_critic_2:  # see deterministic_model parameters
    class: custom.custom_model.CustomCritic # CategoricalMixin # 
    clip_actions: False

memory:
  class: RandomMemory
  memory_size: 8000

agent:
  class: SAC
  gradient_steps: 8
  batch_size: 256

  discount_factor: 0.99
  polyak: 0.005

  random_timesteps: 0
  learning_starts: 200
  actor_learning_rate: 0.0003   # actor learning rate
  critic_learning_rate: 0.0003  # critic learning rate
  grad_norm_clip: 0

  learn_entropy: True
  initial_entropy_value: 0
  activate_contact_sensors: True
  # state_preprocessor: RunningStandardScaler
  # state_preprocessor_kwargs:
  #   size: auto
  #   device: "cuda:0"
  mixed_precision: True


  experiment:
    directory:  'ant'
    experiment_name: 'SAC'
    write_interval: 200
    checkpoint_interval: 500


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 25000
  environment_info: log