params:  

  seed: 42

  env:  
    clip_actions: 1.0
    max_episode_length: 512

  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [512,256]
      activation: elu
      
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  load_checkpoint: False
  load_path: ''

  config:
    name: aloha_direct
    env_name: rlgpu
    sac: true
    multi_gpu: False
    normalize_input: False
    reward_shaper:
      scale_value: 1.0
    max_epochs: 100000
    num_steps_per_episode: 256
    save_best_after: 20
    save_frequency: 20
    gamma: 0.99
    init_alpha: 0.5
    alpha_lr: 0.005
    actor_lr: 0.0005
    critic_lr: 0.0005
    critic_tau: 0.005
    batch_size: 256
    learnable_temperature: true
    num_warmup_steps: 4
    replay_buffer_size: 500000
    num_actors: 64
    device: 'cuda:0'
    device_name: 'cuda:0'
    activate_contact_sensors: True