params:
  seed: 42

  # environment wrapper clipping
  env:
    # added to the wrapper
    # can make custom wrapper?
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  # doesn't have this fine grained control but made it close
  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512]
      activation: elu
      initializer:
          name: default

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: aloha
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: False
    normalize_value: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau : 0.95
    learning_rate: 1e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 5000
    save_best_after: 50
    save_frequency: 25
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 256
    mini_epochs: 16
    critic_coef: 2
    clip_value: True
    seq_length: 4
    bounds_loss_coef: 0.0001
    activate_contact_sensors: True

# params:
#   seed: 42
#   algo:
#     name: a2c_continuous

#   model:
#     name: continuous_a2c_logstd
#   env:
#     clip_actions: 1.0
#   network:
#     name: actor_critic
#     separate: False

#     space:
#       continuous:
#         mu_activation: None
#         sigma_activation: None
#         mu_init:
#           name: default
#         sigma_init:
#           name: const_initializer
#           val: 0
#         fixed_sigma: True
#     mlp:
#       units: [256, 128]
#       activation: elu
#       d2rl: False

#       initializer:
#         name: default
#       regularizer:
#         name: None

#   load_checkpoint: False # flag which sets whether to load the checkpoint
#   load_path: '' # path to the checkpoint to load

#   config:
#     name: WheeledRobotEnv_PPO
#     env_name: rlgpu
#     device: 'cuda:0'
#     device_name: 'cuda:0'
#     multi_gpu: False
#     ppo: True
#     mixed_precision: False
#     normalize_input: True
#     normalize_value: True
#     num_actors: 32 #${....task.env.numEnvs}
#     reward_shaper:
#       scale_value: 0.1
#     normalize_advantage: True
#     gamma: 0.99
#     tau: 0.95
#     learning_rate: 5e-4
#     lr_schedule: adaptive
#     kl_threshold: 0.008
#     score_to_win: 1000000
#     max_epochs: 100000
#     save_best_after: 200
#     save_frequency: 100
#     print_stats: True
#     grad_norm: 1.0
#     entropy_coef: 0.0
#     truncate_grads: True
#     e_clip: 0.2
#     horizon_length: 64 #64
#     minibatch_size: 512
#     mini_epochs: 8
#     critic_coef: 4
#     clip_value: True
#     seq_length: 4
#     bounds_loss_coef: 0.0001
#     activate_contact_sensors: True