seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin # CategoricalMixin # 
    clip_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [32,32]
        activations: elu
    output: ACTIONS
  critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [32,32]
        activations: elu
    output: ONE
  critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [32,32]
        activations: elu
    output: ONE
  target_critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [32,32]
        activations: elu
    output: ONE
  target_critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [32,32]
        activations: elu
    output: ONE

memory:
  class: RandomMemory
  memory_size: 10000

agent:
  class: SAC
  rollouts: 32
  gradient_steps: 8
  batch_size: 64

  discount_factor: 0.99
  polyak: 0.005

  actor_learning_rate: 5.0e-04
  critic_learning_rate: 5.0e-04

  random_timesteps: 0
  learning_starts: 1000

  grad_norm_clip: 1.0

  learn_entropy: True
  entropy_learning_rate: 3.0e-04
  initial_entropy_value: 2
  target_entropy: -1.0
  mixed_precision: True

  experiment:
    directory:  'cartpole_camera_direct'
    experiment_name: 'SAC'
    write_interval: auto
    checkpoint_interval: auto


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 25000
  environment_info: log